### ISSUE TITLE
Issue with  ngram-complete.vim

### ISSUE THREAD

**Issue by boput** [girishji/ngram-complete.vim#1]
Hi again, I am using latest Gvim with patch 1677. Plugin ngram-complete.vim is installed using K-takata minipac under /start directory. Plugin is installed as-is, with its defaults. 

Command :scriptnames shows all vimcomplete and ngram-complete files are loaded. But it seems that ngram-complete data (count_1w.txt, count_2w.txt) files are not loaded, as I am not getting any completion suggestion from ngram-complete (I am getting completion suggestion from vimcomplete after typing some text, nothing from ngram-complete, like show in your demo gif.

vimfiles\pack\minpac\start\vimcomplete\import\vimcompletor.vim|1| 41
vimfiles\pack\minpac\start\vimcomplete\autoload\completor.vim|1| 42
vimfiles\pack\minpac\start\vimcomplete\autoload\recent.vim|1| 43
vimfiles\pack\minpac\start\vimcomplete\autoload\util.vim|1| 44
vimfiles\pack\minpac\start\ngram-complete.vim\autoload\ngcomplete.vim|1| 45
vimfiles\pack\minpac\start\ngram-complete.vim\autoload\options.vim|1| 46
vimfiles\pack\minpac\start\ngram-complete.vim\autoload\unigram.vim|1| 47
vimfiles\pack\minpac\start\ngram-complete.vim\autoload\bigram.vim|1| 48
vimfiles\pack\minpac\start\vimcomplete\plugin\plugins.vim|1| 63
vimfiles\pack\minpac\start\vimcomplete\autoload\abbrev.vim|1| 64
vimfiles\pack\minpac\start\vimcomplete\autoload\buffer.vim|1| 65
vimfiles\pack\minpac\start\vimcomplete\autoload\path.vim|1| 66
vimfiles\pack\minpac\start\vimcomplete\autoload\dictionary.vim|1| 67
vimfiles\pack\minpac\start\vimcomplete\autoload\lsp.vim|1| 68
vimfiles\pack\minpac\start\vimcomplete\plugin\vimcomplete.vim|1| 69
vimfiles\after\plugin\vim-abolish.vim|1| 70

Best,

boput
Thanks for fixing vimcomplete!

**Comment by girishji** [comment]
Did you enable ngram for your filetype? Can you show the output of `:VimCompleteCompletors`?

**Comment by boput** [comment]
This is the output:

{'name': 'path', 'priority': 11, 'completor': function('path#Completor')}
{'name': 'buffer', 'priority': 10, 'completor': function('buffer#Completor')}

**Comment by boput** [comment]
I am using default settings which include 'text' and 'markdown' files.
This are defaults according to  plugin web page:

vim9script
export var options: dict<any> = {
    enable: true,    # Enable this plugin
    priority: 10,    # Higher priority items are shown at the top
    maxCount: 5,     # Maximum number of items shown
    bigram: false,   # 'true' to enable next-word completion
    filetypes: ['text', 'markdown'], # Enable completion for these filetypes only ('*' for all)
    filetypesComments: [], # Enable completion only in comments
}

**Comment by girishji** [comment]
ngram is not enabled. What is the filetype? (`:echo &ft`)

**Comment by boput** [comment]
:echo &filetype -> text

**Comment by boput** [comment]
How do you enable it? Isn't it enabled by default setting:
4. Configuration				*ngram-configuration*

Default options are as follows.
>
	vim9script
	export var options: dict<any> = {
	    enable: true,    # Enable this plugin
	    priority: 10,    # Higher priority items are shown at the top
	    maxCount: 5,     # Maximum number of items shown
	    bigram: false,   # 'true' to enable next-word completion
	    filetypes: ['text', 'markdown'], # Enable completion for these filetypes only ('*' for all)
	    filetypesComments: [], # Enable completion only in comments
	}

**Comment by girishji** [comment]
It should automatically enable if filetype is `text`. Can you paste your whole configuration?

Something like this would work:

```
var vcoptions = {
    ngram: {
        enable: true,
        priority: 10,
        bigram: false,
        filetypes: ['text', 'help', 'markdown'],
        filetypesComments: ['c', 'cpp', 'python', 'java', 'lua', 'vim', 'zsh', 'r'],
    },
}
 
autocmd VimEnter * g:VimCompleteOptionsSet(vcoptions)
```

**Comment by boput** [comment]
I do not have any configuration for ngram-completion. Just plugin installed by K-Takata minpac. Nothing in vimrc.

**Comment by girishji** [comment]
Can you make sure you are installing vimcomplete first, followed by ngram? I think this is likely the problem.

Make sure you do `call minpac#add()` for vimcomplete first. If this does not work, I will debug it by installing minpac on my end.

**Comment by boput** [comment]
This is a part of my vimrc. I am using plugpac, thin wrapper for minpac:

" Must have minpac and plugpac
let s:minpac_dir = $v . '/pack/minpac/opt/minpac'
if !isdirectory(s:minpac_dir)
  echo "Install minpac ..."
  silent! execute printf('!git clone https://github.com/k-takata/minpac.git %s', s:minpac_dir)
end
let s:plugpac_dir = $v . '/autoload'
if !filereadable(expand(s:plugpac_dir . '/plugpac.vim'))
  echo "Install plugpac ..."
  execute 'silent !git clone --depth 1 https://github.com/yukimemi/plugpac.vim ' . s:plugpac_dir . '/autoload'
endif
" ==========================
" /rc is directory for plugin settings/options
let g:plugpac_cfg_path = $v . '/rc'

packadd vimcomplete
packadd ngram-complete.vim

call plugpac#begin()
" ==================
" minpac must have {'type': 'opt'} so that it can be loaded with `packadd`
Pack 'k-takata/minpac', {'type': 'opt'}

" ....other plugins...
Pack 'girishji/vimcomplete', {'type': 'opt'}
Pack 'girishji/ngram-complete.vim', {'type': 'opt'}
"....
call plugpac#end()
"---- end of installing/loading plugins

Output of :scriptnames showing reading/loading vimcomplete and ngram files
It looks vimcomplete files are loaded before ngram files except for vimcompletor.vim

vimfiles\pack\minpac\opt\vimcomplete\plugin\plugins.vim|1| 3
vimfiles\pack\minpac\opt\vimcomplete\autoload\abbrev.vim|1| 4
vimfiles\pack\minpac\opt\vimcomplete\autoload\buffer.vim|1| 5
vimfiles\pack\minpac\opt\vimcomplete\autoload\path.vim|1| 6
vimfiles\pack\minpac\opt\vimcomplete\autoload\dictionary.vim|1| 7
vimfiles\pack\minpac\opt\vimcomplete\autoload\lsp.vim|1| 8
vimfiles\pack\minpac\opt\vimcomplete\autoload\completor.vim|1| 9
vimfiles\pack\minpac\opt\vimcomplete\autoload\recent.vim|1| 10
vimfiles\pack\minpac\opt\vimcomplete\autoload\util.vim|1| 11
vimfiles\pack\minpac\opt\vimcomplete\plugin\vimcomplete.vim|1| 12
vimfiles\pack\minpac\opt\ngram-complete.vim\plugin\ngram-complete.vim|1| 13
vimfiles\pack\minpac\opt\vimcomplete\import\vimcompletor.vim|1| 14
vimfiles\pack\minpac\opt\ngram-complete.vim\autoload\ngcomplete.vim|1| 15
vimfiles\pack\minpac\opt\ngram-complete.vim\autoload\options.vim|1| 16
vimfiles\pack\minpac\opt\ngram-complete.vim\autoload\unigram.vim|1| 17
vimfiles\pack\minpac\opt\ngram-complete.vim\autoload\bigram.vim|1| 18

**Comment by girishji** [comment]
It worked for me after I enabled filetype detection. Try this:
source $VIMRUNTIME/defaults.vim
or
filetype plugin indent on

If this is not the problem, how are you enabling filetype detection?

This plugin manager is turning OFF filetype detection. You can try `:filetype` and compare with `vim --clean`.

My config:

```
" Normally this if-block is not needed, because `:set nocp` is done
" automatically when .vimrc is found. However, this might be useful
" when you execute `vim -u .vimrc` from the command line.
if &compatible
  " `:set nocp` has many side effects. Therefore this should be done
  " only when 'compatible' is set.
  set nocompatible
endif

packadd minpac

call minpac#init()

" minpac must have {'type': 'opt'} so that it can be loaded with `packadd`.
call minpac#add('k-takata/minpac', {'type': 'opt'})

" Add other plugins here.
" call minpac#add('vim-jp/syntax-vim-ex')
call minpac#add('girishji/vimcomplete')
call minpac#add('girishji/ngram-complete.vim')

" Load the plugins right now. (optional)
packloadall

" Define user commands for updating/cleaning the plugins.
" Each of them calls PackInit() to load minpac and register
" the information of plugins, then performs the task.
command! PackUpdate call minpac#update()
command! PackClean  call minpac#clean()
command! PackStatus packadd minpac | call minpac#status()

" source $VIMRUNTIME/defaults.vim
filetype plugin indent on
```

**Comment by girishji** [comment]
In my next update I will make this plugin turn on filetype detection automatically.

**Comment by boput** [comment]
in my vimrc:
if !(exists('g:did_load_filetypes') && exists('g:did_load_ftplugin') && exists('g:did_indent_on'))
  filetype plugin indent on
endif

:filetype -> filetype detection:ON plugin:ON indent:ON

**Comment by boput** [comment]
I have backed up my vimrc configuration. Installed your vimrc, run minpac to install vimcompletion and ngram. Still, I am only getting comletion suggestion from vimcompletion, nothing from ngram.

I am using simplified vim from k-takata, https://github.com/k-takata/vim-kt. I do not think this should cause problems.

Thank you very much for trying to help, but I do not want to waste your time on me.

**Comment by boput** [comment]
vimcompletion will be sufficient for my needs as I am using vim mostly for writing translations of GNU open source programs on translationproject.org into Croatian language, and vimcompletion suggestion are helping.

**Comment by girishji** [comment]
Can you confirm that minpac configuration I posted is working with ngram?

If not can you post output of `:VimCompleteCompletors`?

**Comment by boput** [comment]
As I wrote above, ngram still does not work (after installed your minpac configuration).
Here is output of :VimCompleteCompletors
{'name': 'path', 'priority': 11, 'completor': function('path#Completor')}
{'name': 'buffer', 'priority': 10, 'completor': function('buffer#Completor')}

**Comment by girishji** [comment]
Ok, I found a possible issue. I will commit the fix in a few hours and let you know.

**Comment by boput** [comment]
Okay, thanks.

**Comment by girishji** [comment]
I comitted a new version. Can you give it a try and see if it makes a difference?

**Comment by boput** [comment]
Minpac updated vimcomplete. Loaded one .txt and one .md file.  No ngram suggestion, only from vimcomplete {buffer].
Same output from :VimCompleteCompletors

output of :scripnames
  1: ~\vimfiles\vimrc
  2: ~\vimfiles\pack\minpac\opt\minpac\plugin\minpac.vim
  3: ~\vimfiles\pack\minpac\opt\minpac\autoload\minpac.vim
  4: ~\vimfiles\pack\minpac\opt\vimcomplete\plugin\plugins.vim
  5: ~\vimfiles\pack\minpac\opt\vimcomplete\autoload/abbrev.vim
  6: ~\vimfiles\pack\minpac\opt\vimcomplete\autoload/buffer.vim
  7: ~\vimfiles\pack\minpac\opt\vimcomplete\autoload/path.vim
  8: ~\vimfiles\pack\minpac\opt\vimcomplete\autoload/dictionary.vim
  9: ~\vimfiles\pack\minpac\opt\vimcomplete\autoload\completor.vim
 10: ~\vimfiles\pack\minpac\opt\vimcomplete\autoload\recent.vim
 11: ~\vimfiles\pack\minpac\opt\vimcomplete\autoload\util.vim
 12: ~\vimfiles\pack\minpac\opt\vimcomplete\plugin\vimcomplete.vim
 13: C:\Root\vim-kt-win64\runtime\filetype.vim
 14: C:\Root\vim-kt-win64\runtime\menu.vim
 15: C:\Root\vim-kt-win64\runtime\autoload\paste.vim
 16: C:\Root\vim-kt-win64\runtime\ftplugin.vim
 17: ~\vimfiles\pack\minpac\opt\ngram-complete.vim\plugin\ngram-complete.vim
 18: ~\vimfiles\pack\minpac\opt\vimcomplete\import\vimcompletor.vim
 19: ~\vimfiles\pack\minpac\opt\ngram-complete.vim\autoload/ngcomplete.vim
 20: ~\vimfiles\pack\minpac\opt\ngram-complete.vim\autoload/options.vim
 21: ~\vimfiles\pack\minpac\opt\ngram-complete.vim\autoload/unigram.vim
 22 A: ~\vimfiles\pack\minpac\opt\ngram-complete.vim\autoload/bigram.vim

**Comment by boput** [comment]
In addition to previous :VimCompleteCompletor output got in addition this line:
{'name': 'ngram', 'priority': 10, 'completor': function('ngcomplete#Completor')}

Still no ngram completions.

**Comment by boput** [comment]
Please note that in vimrc there is no any option for ngram no for vimcomplete. Meaning both plugins are the only source for those   loaded. If you want me to put some options in vimrc, let me know.

**Comment by girishji** [comment]
Are you on windows? or linux?

**Comment by girishji** [comment]
I made some changes to path separator. Try again.

**Comment by boput** [comment]
Excellent, I am now getting ngram suggestions!
[ngram] on top, [buffer] after [ngram]

Yes, on Windows, but I will also try it on WSL Linux (Debian and/or Ubuntu) tomorrow (it's late over here, +9 hours with SF).

**Comment by girishji** [comment]
You can change priority to reorder what appears on top. You can also mix them up. Good luck!

**Comment by boput** [comment]
Thanks!
