### ISSUE TITLE
complete common words

### ISSUE THREAD

**Issue by Konfekt** [girishji/ngram-complete.vim#2]
Just discovered this. Seems like we tackled the same problem. Maybe https://github.com/Konfekt/complete-common-words.vim/ values a mention for other tongues

**Comment by Konfekt** [comment]
I found to get by well with the say 10 000 most common words; feel free to expand your database by these dictionaries or reach out to team up

**Comment by girishji** [comment]
Is this really useful? I found that it rarely suggests appropriate words, and it has 333,333 words in 1-gram. Bigram is a little better. There are also massive n-gram files from google but reading them (into a trie) costs startup time. Maybe an external process (like language-server) helps. Vim can invoke external .so libraries but it is not portable for a plugin. I also think a context aware word suggestion is the best, but it requires lot of compute.

**Comment by Konfekt** [comment]
I'd wager yes. For example, `superf` completes to `superficial` rather than `superfamilies` or `superfatted`. I find that commonly I complete common words.

**Comment by Konfekt** [comment]
Of course the more context the better to complete (says ChatGPT), but I'm somehow reluctant to have terabytes of dictionaries in my Vim plug-in directory.

**Comment by girishji** [comment]
1-gram doesn't complete `superf` but completes `super`.  Would you like to add your 10,000 words into the 1-gram dictionary (need to be sorted)?

<img width="304" alt="Screenshot 2024-12-04 at 12 08 09 AM" src="https://github.com/user-attachments/assets/f3dc3d0a-6ab4-4740-96f5-9fa2105ab331">

**Comment by Konfekt** [comment]
>  (need to be sorted)

Alphabetically? Asking, because the whole point of my plug-in is that the words are sorted by frequency

**Comment by girishji** [comment]
Sorted by frequency. See `count_1w.txt`. The number next to word is frequency. It is from google ngram database. I don't know what corpus they learned from. Yours is from different corpus. You can just prepend yours I suppose, without need to merge.
