### ISSUE TITLE
adapt 1gram to &spelllang

### ISSUE THREAD

**Issue by Konfekt** [girishji/ngram-complete.vim#4]
Since adding some 1grams in https://github.com/girishji/ngram-complete.vim/pull/3#issuecomment-2522432085 was easy, how about adding the 1grams and `spelllang` autocmd's from https://github.com/Konfekt/complete-common-words.vim/blob/master/plugin/complete-common-words.vim to improve completion for a few other common tongues?

**Comment by girishji** [comment]
You are welcome to add it, and send PR.
